title	_TITLE_
root	_ROOTDEV_
kernel	/vmlinuz root=/dev/ram0 rw rdinit=linuxrc boot=_DEVNAME_ lang=en remote=default_remote receiver=default_receiver keymap=qwerty splash=silent vga=789 video=vesafb:ywrap,mtrr _HDTV_ _DEBUG_ _CONFIG_
initrd  /initrd.gz
boot
