transmission:
  usr: enter_same_username_as_in_transmission_settings_file
  pwd: enter_same_password_as_in_transmission_settings_file
showrss:
  usr: http://showrss.info/rss.php?user_id=ENTERYOURSHOWRSSUSERIDHERE&hd=2&proper=1&raw=true
trakt:
  usr: enter_your_trakt.tv_username
  pwd: enter_your_trakt.tv_password
  api: enter_your_trakt.tv_apikey
  